# Generated by Django 5.2.13 on 2026-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField()),
            ],
            options={
                'db_table': 'contact_data',
            },
        ),
    ]
