# Generated by Django 5.2.13 on 2026-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_contact_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('old', models.IntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact_data',
            name='Message',
            field=models.CharField(max_length=500),
        ),
    ]
