# Generated by Django 5.2.13 on 2026-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product_alter_contact_data_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='confirm_password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
